# 端口
server:
  port: 6791

spring:
    data:
      mongodb:
         uri: mongodb://localhost:27017/BI


jsonSource: /Users/purchaser/Desktop/商务智能/result/result3.json
jsonSourceDir: /Users/purchaser/Desktop/商务智能/result/3-8
