# 端口
server:
  port: 6791

spring:
    data:
      mongodb:
         uri: mongodb://localhost:27017/BI

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


jsonSource: /Users/purchaser/Desktop/商务智能/result/result9.json
jsonSourceDir: /Users/purchaser/Desktop/商务智能/result
