# 端口
server:
  port: 6791

spring:
  application:
    name: MongoDAO
  data:
      mongodb:
         uri: mongodb://localhost:27017/BI

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/


jsonSource: /Users/purchaser/Desktop/商务智能/result/result1.json
jsonSourceDir: /Users/purchaser/Desktop/商务智能/result/part
